"use client";

import FeatureCard from "@/components/ui/FeatureCard";
import ReiLabel from "@/components/ui/ReiLabel";
import { motion } from "framer-motion";
import {
  container,
  item,
  lineContainer,
  lineItem,
} from "@/lib/variantsAnimation";
import { useRef, useState } from "react";

const data = [
  {
    id: 0,
    icon: "/icons/cashFlow.png",
    images: [
      "/img-optimized/Fundamentals1.webp",
      "/img-optimized/Fundamentals2.webp",
      "/img-optimized/Fundamentals3.webp",
    ],
    title: "Cash Flow",
    description:
      "The net income generated by a property after all expenses are paid.",
  },
  {
    id: 1,
    icon: "/icons/instantEquity.png",
    images: [
      "/img-optimized/Market1.webp",
      "/img-optimized/Market2.webp",
      "/img-optimized/Market3.webp",
    ],
    title: "Instant Equity",
    description:
      "The difference between a property's purchase price and its estimated market value at the time of acquisition.",
  },
  {
    id: 2,
    icon: "/icons/leverage.svg",
    images: [
      "/img-optimized/Financing1.webp",
      "/img-optimized/Financing2.webp",
      "/img-optimized/Financing3.webp",
    ],
    title: "Leverage",
    description:
      "Using borrowed capital to increase the potential return of an investment.",
  },
  {
    id: 3,
    icon: "/icons/principalPaydown.png",
    images: [
      "/img-optimized/Property1.webp",
      "/img-optimized/Property2.webp",
      "/img-optimized/Property3.webp",
    ],
    title: "Principal Paydown",
    description:
      "The gradual reduction of mortgage debt, effectively paid by tenants' rent.",
  },
  {
    id: 4,
    icon: "/icons/marketAppreciation.png",
    images: [
      "/img-optimized/Managing1.webp",
      "/img-optimized/Managing2.webp",
      "/img-optimized/Managing3.webp",
    ],
    title: "Market Appreciation",
    description:
      "The increase in a property's value over time due to market factors.",
  },
  {
    id: 5,
    icon: "/icons/forcedAppreciation.png",
    images: [
      "/img-optimized/Exit1.webp",
      "/img-optimized/Exit2.webp",
      "/img-optimized/Exit3.webp",
    ],
    title: "Forced Appreciation",
    description:
      "Actively increasing a property's value through improvements or better management.",
  },
  {
    id: 6,
    icon: "/icons/taxAdvantages.png",
    images: [
      "/img-optimized/Exit1.webp",
      "/img-optimized/Exit2.webp",
      "/img-optimized/Exit3.webp",
    ],
    title: "Tax Advantages",
    description:
      "Various tax benefits and deductions available to real estate investors.",
  },
  {
    id: 7,
    icon: "/icons/refinancing.png",
    images: [
      "/img-optimized/Exit1.webp",
      "/img-optimized/Exit2.webp",
      "/img-optimized/Exit3.webp",
    ],
    title: "Refinancing",
    description:
      "Using profits and equity from existing investments to acquire additional properties or improve current ones.",
  },
];

export default function Stats() {
  const [showPopUpId, setShowPopUpId] = useState<number | null>(null);
  const [popUpPosition, setPopUpPosition] = useState({
    top: 0,
    left: 0,
    width: 0,
    height: 0,
  });
  const refs = useRef<(HTMLDivElement | null)[]>([]);

  function handleHover(id: number) {
    const rect = refs.current[id]?.getBoundingClientRect();
    if (!rect) return;
    console.log(id);
    setShowPopUpId(id);
    setPopUpPosition({
      top: rect.top,

      left: rect.left,
      width: rect.width,
      height: rect.height,
    });
  }

  return (
    <section className="relative overflow-hidden">
      <motion.div
        variants={container}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-50px" }}
        id="Stats"
        className="section-default "
      >
        <div>
          <div className="mx-auto space-y-12 text-center ">
            <motion.h2 className="h2-large" variants={item}>
              Why the Industry Is
              <span className="gradient-text text-bold"> Shifting</span>
            </motion.h2>

            <div className="space-y-8">
              <motion.h4 variants={item}>
                The old play—“it’ll be worth more next year”—isn’t a plan.
              </motion.h4>
              <motion.h4 variants={item} className="max-w-[700px] mx-auto">
                Pre‑construction is mostly an appreciation bet (useful in some
                cycles), but it’s just{" "}
                <span className="gradient-text font-bold">one of eight</span>{" "}
                profit centres.
              </motion.h4>
              <motion.h4 variants={item}>
                With renewals squeezing households, clients want{" "}
                <span className="gradient-text font-bold">
                  numbers‑first guidance
                </span>{" "}
                that works in any market. The agents who can underwrite
                deals—and{" "}
                <span className="gradient-text font-bold">
                  stack all eight profit centres
                </span>
                —win now.
              </motion.h4>
            </div>
          </div>
        </div>

        <motion.div className="mt-15" variants={item}>
          <ReiLabel />
        </motion.div>

        {showPopUpId != null && (
          <div
            className={`absolute p-3 bg-white border border-gray-400 text-black max-w-[240px] z-100 rounded-2xl shadow-classic -translate-x-1/2 left-1/2 max-[768px]:translate-y-[100%]` }
            style={
              {
                // top: popUpPosition.top - 60, // 60px выше элемента (можно настроить)
              }
            }
          >
            <span className="gradient-text font-bold">
              {" "}
              {data[showPopUpId].title}:{" "}
            </span>
            {data[showPopUpId].description}
          </div>
        )}
        <motion.div className="relative w-full h-full">
          <div className="absolute top-0 bottom-0 left-1/2 transform -translate-x-1/2 max-w-[400px] w-full h-[600px]">
            {/* MOBILE lineS */}
            <motion.div
              variants={lineContainer}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              className="absolute left-1/2 -translate-x-1/2 top-[-35px] w-full max-w-[380px] h-[716px] max-[600px]:px-[60px] justify-between pointer-events-none z-0 hidden max-[1024px]:flex"
            >
              <motion.svg
                className="w-full h-[716px]"
                viewBox="0 0 259 716"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                preserveAspectRatio="none"
              >
                <motion.path
                  d="M0 109.5C0 109.5 82 109.5 85.5 109.5C89 109.5 113 109.5 121.5 101C130 92.5 129.5 67.5 129.5 67.5V0"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M0 312.5C0 312.5 82 312.5 85.5 312.5C89 312.5 113 312.5 121.5 304C130 295.5 129.5 270.5 129.5 270.5V0"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M0 513.5C0 513.5 82 513.5 85.5 513.5C89 513.5 113 513.5 121.5 505C130 496.5 129.5 471.5 129.5 471.5V0"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M258.505 109.5C258.505 109.5 176.505 109.5 173.005 109.5C169.505 109.5 145.505 109.5 137.005 101C128.505 92.5 129.005 67.5 129.005 67.5V0"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M258.505 312.5C258.505 312.5 176.505 312.5 173.005 312.5C169.505 312.5 145.505 312.5 137.005 304C128.505 295.5 129.005 270.5 129.005 270.5V0"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M258.505 513.5C258.505 513.5 176.505 513.5 173.005 513.5C169.505 513.5 145.505 513.5 137.005 505C128.505 496.5 129.005 471.5 129.005 471.5V0"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M0 715.5C0 715.5 82 715.5 85.5 715.5C89 715.5 113 715.5 121.5 707C130 698.5 129.5 673.5 129.5 673.5V202"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M258.505 715.5C258.505 715.5 176.505 715.5 173.005 715.5C169.505 715.5 145.505 715.5 137.005 707C128.505 698.5 129.005 673.5 129.005 673.5V0.129836"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
              </motion.svg>
            </motion.div>

            {/* DESKTOP lineS */}
            <motion.div
              variants={lineContainer}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              className="absolute left-1/2 -translate-x-1/2 top-[-35px] w-[971px] h-[293px] justify-between pointer-events-none z-0 hidden min-[1024px]:flex "
            >
              <motion.svg
                width="1122"
                height="292"
                viewBox="0 0 1122 292"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <motion.path
                  d="M1 143.75C1 -0.253509 561 108.627 561 0.75"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M1121 143.75C1121 -0.253509 561 108.627 561 0.75"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M137 205.75C137 62.25 561 108.25 561 0.75"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M985 205.75C985 62.25 561 108.25 561 0.75"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M294 288.75C294 145 561 108.437 561 0.75"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M828 288.75C828 145 561 108.437 561 0.75"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M470 291.75C470 148.003 561 108.435 561 0.75"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
                <motion.path
                  d="M652 291.75C652 147.977 561 108.454 561 0.75"
                  stroke="#B34AE4"
                  variants={lineItem}
                />
              </motion.svg>
            </motion.div>
          </div>
        </motion.div>
        <motion.div
          variants={container}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-50px" }}
          className="grid grid-cols-2 gap-y-[65px] justify-start pt-[30px] w-full max-w-[700px] mx-auto lg:hidden"
        >
          {data.map((props, i) => (
            <motion.div
              key={i}
              variants={item}
              onTouchStart={() => handleHover(props.id)}
              onTouchEnd={() => setShowPopUpId(null)}
            >
              <FeatureCard {...props} />
            </motion.div>
          ))}
        </motion.div>

        {/*  DESKTOP ICONS */}
        <motion.div
          variants={container}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-50px" }}
          className="relative w-full max-w-[1200px] mx-auto min-h-[400px] hidden lg:flex "
        >
          <div className="absolute pointer-events-none w-full left-1/2 top-[88%] -translate-x-[50%] -translate-y-[255px] flex justify-center gap-[890px]">
            {[data[0], data[5]].map((props, i) => (
              <motion.div
                onHoverStart={() => handleHover(props.id)}
                onHoverEnd={() => setShowPopUpId(null)}
                ref={(el) => {
                  refs.current[props.id] = el;
                }}
                key={i}
                variants={item}
                className="pointer-events-auto"
              >
                <FeatureCard {...props} />
              </motion.div>
            ))}
          </div>

          <div className="absolute pointer-events-none w-full left-1/2 top-[85%] -translate-x-[50%] -translate-y-[190px] flex justify-center  gap-[638px]">
            {[data[1], data[4]].map((props, i) => (
              <motion.div
                className="pointer-events-auto"
                onHoverStart={() => handleHover(props.id)}
                onHoverEnd={() => setShowPopUpId(null)}
                ref={(el) => {
                  refs.current[props.id] = el;
                }}
                key={i}
                variants={item}
              >
                <FeatureCard {...props} />
              </motion.div>
            ))}
          </div>

          <div className="absolute pointer-events-none w-full left-1/2 top-[82%] -translate-x-[50%] -translate-y-[130px] flex justify-center gap-[348px]">
            {[data[6], data[7]].map((props, i) => (
              <motion.div
                className="pointer-events-auto"
                onHoverStart={() => handleHover(props.id)}
                onHoverEnd={() => setShowPopUpId(null)}
                ref={(el) => {
                  refs.current[props.id] = el;
                }}
                key={i}
                variants={item}
              >
                <FeatureCard {...props} />
              </motion.div>
            ))}
          </div>

          <div className="absolute pointer-events-none w-full left-1/2 top-[75%] -translate-x-[50%] -translate-y-1/2 flex justify-center gap-[60px]">
            {[data[2], data[3]].map((props, i) => (
              <motion.div
                className="pointer-events-auto"
                onHoverStart={() => handleHover(props.id)}
                onHoverEnd={() => setShowPopUpId(null)}
                ref={(el) => {
                  refs.current[props.id] = el;
                }}
                key={i}
                variants={item}
              >
                <FeatureCard {...props} />
              </motion.div>
            ))}
          </div>
        </motion.div>
      </motion.div>
    </section>
  );
}
